Repository sopt-makers/makers-page, pull requests merged in 2023-07, with the labels that each got.

#1 chore: actions 추가
  .github/workflows/build-web.yml
  .github/workflows/check.yml
  .github/workflows/deploy-development.yml
  apps/web/src/app/error.tsx
  apps/web/src/env.ts
  apps/web/src/env/server.ts
  apps/web/src/gateway/internal.ts
  apps/web/turbo.json
Labels: size/L

#3 feat: 코드블럭 구현
  apps/ssr-gateway/src/worker.ts
  apps/web/package.json
  apps/web/src/components/notion/renderer/BlockResolver.tsx
  apps/web/src/components/notion/renderer/SyntaxHighlighter.tsx
  yarn.lock
Labels: size/L

#5 feat: 블로그 기초 기능 구현
  apps/ssr-gateway/.dev.vars.example
  apps/ssr-gateway/package.json
  apps/ssr-gateway/src/notion/index.ts
  apps/ssr-gateway/src/notion/property.ts
  apps/ssr-gateway/src/notion/types.ts
  apps/ssr-gateway/src/router/blog.ts
  apps/ssr-gateway/src/router/index.ts
  apps/ssr-gateway/src/trpc/context.ts
  apps/ssr-gateway/src/worker.ts
  apps/web/package.json
  apps/web/src/app/blog/article/[id]/page.tsx
  apps/web/src/app/blog/category/[category]/page.tsx
  apps/web/src/app/blog/page.tsx
  apps/web/src/components/blog/ArticleDetail.tsx
  apps/web/src/components/blog/ArticleList.tsx
  apps/web/tailwind.config.js
  yarn.lock
Labels: size/XL

#4 feat: 폰트와 테마 적용
  apps/web/src/app/SUIT-Bold.woff2
  apps/web/src/app/SUIT-Light.woff2
  apps/web/src/app/SUIT-Medium.woff2
  apps/web/src/app/SUIT-Regular.woff2
  apps/web/src/app/SUIT-SemiBold.woff2
  apps/web/src/app/global.css
  apps/web/src/app/layout.tsx
  apps/web/tailwind.config.js
  packages/eslint-config-custom/index.js
Labels: size/M

#6 feat: 메인페이지 퍼블리싱
  apps/web/src/app/global.css
  apps/web/src/app/page.tsx
  apps/web/src/components/header/Header.tsx
  apps/web/src/components/mainpage/Archive.tsx
  apps/web/src/components/mainpage/CoreValue.tsx
  apps/web/src/components/mainpage/Greeting.tsx
  apps/web/src/components/mainpage/MakersIntodution.tsx
  apps/web/src/components/mainpage/Product.tsx
  apps/web/src/components/mainpage/RecruitBanner.tsx
  apps/web/tailwind.config.js
Labels: size/L

#7 chore: ssr gateway 배포 추가
  .github/workflows/deploy-development.yml
Labels: size/XS

#9 chore: ssr gateway 배포 오류 해결
  .github/workflows/deploy-development.yml
Labels: size/XS

#8 feat: framer motion 환경 셋업
  apps/web/package.json
  apps/web/src/app/layout.tsx
  apps/web/src/app/loading.tsx
  apps/web/src/app/page.tsx
  apps/web/src/components/core/animation/AnimationProviders.tsx
  yarn.lock
Labels: size/M

#10 chore: 배포 스크립트 변경
  .github/workflows/build-web.yml
  .github/workflows/deploy-development.yml
Labels: size/M

#11 feat: 3D 메이커스 로고 적용
  apps/web/package.json
  apps/web/public/logo-transformed.glb
  apps/web/src/app/page.tsx
  apps/web/src/components/common/MakersLogo3D/MakersLogoModel.tsx
  apps/web/src/components/common/MakersLogo3D/index.tsx
  yarn.lock
Labels: size/XL

#13 feat: 부드러운 스크롤 추가
  apps/web/package.json
  apps/web/src/app/page.tsx
  yarn.lock
Labels: size/L

#16 feat: 루트 폰트 크기 변경
  apps/web/src/app/layout.tsx
  apps/web/src/components/header/Header.tsx
  apps/web/src/components/mainpage/Archive.tsx
  apps/web/src/components/mainpage/CoreValue.tsx
  apps/web/src/components/mainpage/ProductSection.tsx
  apps/web/src/components/mainpage/Recruit.tsx
  apps/web/src/components/mainpage/greeting/GreetingSection.tsx
  apps/web/src/components/mainpage/greeting/Intro.tsx
  apps/web/src/components/mainpage/greeting/MakersIntodution.tsx
  apps/web/src/components/mainpage/greeting/Missions.tsx
  apps/web/src/components/mainpage/prouduct/Description.tsx
  apps/web/tailwind.config.js
Labels: size/M

#17 fix: 3d 로고 렌더링 오류 해결
  apps/web/src/components/mainpage/greeting/GreetingSection.tsx
Labels: size/XS

#18 chore: Tailwind 관련 세팅 변경
  .prettierrc.js
  .vscode/settings.json
  package.json
  prettier.config.js
  yarn.lock
Labels: size/S

#19 fix: 폰트 적용 안되는 오류 수정
  apps/web/src/app/layout.tsx
Labels: size/XS

#14 feat: 후기 섹션 구현
  apps/web/src/app/page.tsx
  apps/web/src/components/mainpage/feedback/FeedbackCard.tsx
  apps/web/src/components/mainpage/feedback/FeedbackSection.tsx
  apps/web/src/components/mainpage/feedback/data.ts
  apps/web/src/components/mainpage/feedback/icons.tsx
  apps/web/tailwind.config.js
Labels: size/L

#15 feat: 노션 이미지 처리 구현
  apps/ssr-gateway/package.json
  apps/ssr-gateway/src/notion/index.ts
  apps/ssr-gateway/src/router/blog.ts
  apps/ssr-gateway/src/router/recruit.ts
  apps/ssr-gateway/src/trpc/context.ts
  apps/ssr-gateway/src/worker.ts
  apps/ssr-gateway/wrangler.toml
  apps/web/src/components/notion/renderer/BlockResolver.tsx
  yarn.lock
Labels: size/L

#20 feat: greeting 문구별 애니메이션 추가
  apps/web/src/app/page.tsx
  apps/web/src/components/mainpage/ProductSection.tsx
  apps/web/src/components/mainpage/greeting/GreetingSection.tsx
  apps/web/src/components/mainpage/greeting/Intro.tsx
  apps/web/src/components/mainpage/greeting/MakersIntodution.tsx
  apps/web/src/components/mainpage/greeting/Missions.tsx
  apps/web/src/components/mainpage/prouduct/Description.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/src/components/mainpage/prouduct/Title.tsx
Labels: size/L

#21 feat: Core Value 섹션 구현
  apps/web/src/app/page.tsx
  apps/web/src/components/common/HorizontalScroll.tsx
  apps/web/src/components/common/InspectableBox.tsx
  apps/web/src/components/mainpage/CoreValue.tsx
  apps/web/src/components/mainpage/coreValue/CoreValueSection.tsx
  apps/web/src/components/mainpage/coreValue/FlipableCard.tsx
  apps/web/src/components/mainpage/coreValue/ValueCard.tsx
  apps/web/src/components/mainpage/coreValue/images.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/src/components/mainpage/prouduct/Title.tsx
  apps/web/src/components/notion/renderer/BlockResolver.tsx
  apps/web/src/util/useDomInspect.ts
  apps/web/tailwind.config.js
  packages/eslint-config-custom/index.js
Labels: size/XL

#23 refactor: 타입스크립트 strict 적용
  apps/web/src/components/blog/ArticleDetail.tsx
  apps/web/src/components/blog/ArticleList.tsx
  apps/web/src/components/mainpage/feedback/FeedbackCard.tsx
  apps/web/src/components/mainpage/greeting/Intro.tsx
  apps/web/src/components/recruit/ImageBlock.tsx
  apps/web/src/components/recruit/recruitBlockComponents.tsx
  apps/web/src/gateway/index.ts
  packages/tsconfig/nextjs.json
Labels: size/S

#24 feat: Notion API 가져오는 방식 변경
  apps/ssr-gateway/package.json
  apps/ssr-gateway/src/exports.ts
  apps/ssr-gateway/src/notion/api/client.ts
  apps/ssr-gateway/src/notion/api/rawApi.ts
  apps/ssr-gateway/src/notion/officialApi/client.ts
  apps/ssr-gateway/src/notion/officialApi/index.ts
  apps/ssr-gateway/src/notion/officialApi/pagination.ts
  apps/ssr-gateway/src/notion/officialApi/property.ts
  apps/ssr-gateway/src/notion/officialApi/types.ts
  apps/ssr-gateway/src/router/blog.ts
  apps/ssr-gateway/src/router/index.ts
  apps/ssr-gateway/src/router/internal.ts
  apps/ssr-gateway/src/router/recruit.ts
  apps/ssr-gateway/src/trpc/context.ts
  apps/ssr-gateway/src/worker.ts
  apps/web/package.json
  apps/web/src/app/recruit/[id]/page.tsx
  apps/web/src/app/recruit/page.tsx
  apps/web/src/components/blog/ArticleDetail.tsx
  apps/web/src/components/blog/blogBlockComponents.tsx
  apps/web/src/components/notion/official/BlockRenderer.tsx
  apps/web/src/components/notion/official/BlockResolver.tsx
  apps/web/src/components/notion/official/RichTextRenderer.tsx
  apps/web/src/components/notion/official/SyntaxHighlighter.tsx
  apps/web/src/components/notion/unofficial/BlockRenderer.tsx
  apps/web/src/components/notion/unofficial/BlockResolver.tsx
  apps/web/src/components/notion/unofficial/TextRenderer.tsx
  apps/web/src/components/notion/unofficial/types.ts
  apps/web/src/components/recruit/ContentBlock.tsx
  apps/web/src/components/recruit/ImageBlock.tsx
  apps/web/src/components/recruit/recruitBlockComponents.tsx
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
  yarn.lock
Labels: size/XL

#25 feat: 브라우저 게이트웨이 접근 추가
  apps/ssr-gateway/src/router/recruit.ts
  apps/ssr-gateway/src/trpc/stub.ts
  apps/web/.env.development
  apps/web/package.json
  apps/web/src/app/admin/api/revalidate/[slug]/route.ts
  apps/web/src/app/admin/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/app/trpc/[[...slug]]/route.ts
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
  apps/web/src/env/server.ts
  apps/web/src/gateway/GatewayProvider.tsx
  apps/web/src/gateway/browser.ts
  apps/web/src/gateway/index.ts
  apps/web/src/gateway/serviceBinding.ts
  apps/web/turbo.json
  yarn.lock
Labels: size/L

#26 chore: 프로덕션 배포 추가
  .github/workflows/deploy-production.yml
Labels: size/M

#27 chore: 워크플로 이름 변경
  .github/workflows/deploy-production.yml
Labels: size/XS

#31 feat: 리크루팅 페이지 페치 정책 변경
  apps/ssr-gateway/src/notion/api/client.ts
  apps/ssr-gateway/src/notion/officialApi/index.ts
  apps/ssr-gateway/src/router/recruit.ts
  apps/ssr-gateway/src/trpc/context.ts
  apps/ssr-gateway/src/worker.ts
  apps/web/src/app/recruit/[[...slug]]/error.tsx
  apps/web/src/app/recruit/[[...slug]]/loading.tsx
  apps/web/src/app/recruit/[[...slug]]/not-found.tsx
  apps/web/src/app/recruit/[[...slug]]/page.tsx
  apps/web/src/app/recruit/[id]/error.tsx
  apps/web/src/app/recruit/[id]/page.tsx
  apps/web/src/app/trpc/[[...slug]]/route.ts
  apps/web/src/gateway/browser.ts
Labels: size/L

#29 refactor: 색상 이름 정리
  apps/web/src/components/mainpage/feedback/FeedbackSection.tsx
  apps/web/src/components/mainpage/greeting/MakersIntodution.tsx
  apps/web/src/components/mainpage/greeting/Missions.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/src/components/mainpage/prouduct/Title.tsx
  apps/web/tailwind.config.js
Labels: size/M

#30 feat: productSection 인터랙션 수정 및 추상화
  apps/web/src/components/mainpage/prouduct/Description.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/src/components/mainpage/prouduct/Title.tsx
  apps/web/src/components/mainpage/prouduct/data.ts
Labels: size/L

#32 feat: 리크루트 스타일 개선
  .prettierrc.js
  apps/web/src/app/recruit/[[...slug]]/layout.tsx
  apps/web/src/app/recruit/[[...slug]]/page.tsx
  apps/web/src/components/notion/unofficial/TextRenderer.tsx
  apps/web/src/components/notion/unofficial/colors.ts
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
  apps/web/tailwind.config.js
Labels: size/L

#28 feat: 메타데이터 적용
  apps/web/src/app/favicon.ico
  apps/web/src/app/layout.tsx
  apps/web/src/app/opengraph-image.png
Labels: size/S

#34 feat: 테이블 블럭 구현
  apps/web/src/components/notion/unofficial/BlockResolver.tsx
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
  apps/web/src/components/recruit/table/TableBlock.tsx
  apps/web/src/components/recruit/table/TableRowBlock.tsx
  apps/web/src/components/recruit/table/context.tsx
Labels: size/L

#35 fix: 메타데이터 수정
  apps/web/src/app/layout.tsx
  apps/web/turbo.json
Labels: size/XS

#33 feat: 시간에 따른 recruitButton 문구 변경
  apps/web/src/components/common/RecruitButton.tsx
  apps/web/src/components/mainpage/Recruit.tsx
  apps/web/src/components/mainpage/greeting/Intro.tsx
  package.json
  yarn.lock
Labels: size/M

#36 feat: GreetingSection 모바일 대응
  apps/web/src/components/common/RecruitButton.tsx
  apps/web/src/components/mainpage/greeting/GreetingSection.tsx
  apps/web/src/components/mainpage/greeting/Intro.tsx
  apps/web/src/components/mainpage/greeting/MakersIntodution.tsx
  apps/web/src/components/mainpage/greeting/Missions.tsx
Labels: size/M

#37 feat: ProductSection 모바일 대응
  apps/web/src/components/mainpage/prouduct/Description.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/src/components/mainpage/prouduct/Title.tsx
Labels: size/M

#38 feat: RecruitSection 모바일 대응
  apps/web/src/app/page.tsx
  apps/web/src/components/mainpage/recruit/RecruitSection.tsx
Labels: size/S

#39 refactor: 메이커스 로고 애니메이션 수정
  apps/web/src/components/mainpage/greeting/GreetingSection.tsx
  apps/web/src/components/mainpage/greeting/Intro.tsx
Labels: size/S

#40 feat: Core Value & 활동후기 모바일 버전 구현
  apps/web/src/app/page.tsx
  apps/web/src/components/mainpage/coreValue/CenterFlipper.tsx
  apps/web/src/components/mainpage/coreValue/CoreValueDesktop.tsx
  apps/web/src/components/mainpage/coreValue/CoreValueMobile.tsx
  apps/web/src/components/mainpage/coreValue/CoreValueSection.tsx
  apps/web/src/components/mainpage/coreValue/FlipableCard.tsx
  apps/web/src/components/mainpage/coreValue/ValueCard.tsx
  apps/web/src/components/mainpage/coreValue/cardData.tsx
  apps/web/src/components/mainpage/coreValue/images.tsx
  apps/web/src/components/mainpage/feedback/FeedbackCard.tsx
  apps/web/src/components/mainpage/feedback/FeedbackSection.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
Labels: size/XL

#41 feat: 리크루팅 페이지 처리 수정
  apps/ssr-gateway/src/router/recruit.ts
  apps/web/src/app/loading.tsx
  apps/web/src/app/recruit/[[...slug]]/layout.tsx
  apps/web/src/app/recruit/[[...slug]]/loading.tsx
  apps/web/src/app/recruit/[[...slug]]/page.tsx
  apps/web/src/app/recruit/layout.tsx
  apps/web/src/components/common/icons/MakersLogo.tsx
  apps/web/src/components/notion/unofficial/types.ts
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
Labels: size/L

#42 feat: floating 요소 구현
  apps/web/src/app/page.tsx
  apps/web/src/components/common/RightArrowIcon.tsx
  apps/web/src/components/mainpage/floating/FloatingSection.tsx
  apps/web/src/components/mainpage/floating/Footer.tsx
  apps/web/src/components/mainpage/floating/Header.tsx
  apps/web/src/components/mainpage/greeting/MakersIntodution.tsx
Labels: size/M

#43 chore: greeting 디자인 QA 사항 반영
  apps/web/src/components/mainpage/greeting/MakersIntodution.tsx
  apps/web/src/components/mainpage/greeting/Missions.tsx
  apps/web/tailwind.config.js
Labels: size/S

#44 feat: 로딩 UI 개선
  apps/web/src/app/(main)/layout.tsx
  apps/web/src/app/(main)/loading.tsx
  apps/web/src/app/(main)/page.tsx
  apps/web/src/components/common/FullscreenLoading.tsx
  apps/web/src/components/common/RecruitButton.tsx
  apps/web/src/components/common/RenderingLoading.tsx
  apps/web/src/components/mainpage/coreValue/CenterFlipper.tsx
  apps/web/src/components/mainpage/coreValue/CoreValueMobile.tsx
  apps/web/src/components/mainpage/coreValue/FlipableCard.tsx
  apps/web/src/components/mainpage/coreValue/ValueCard.tsx
  apps/web/src/components/mainpage/feedback/FeedbackCard.tsx
  apps/web/src/components/mainpage/feedback/FeedbackSection.tsx
  apps/web/src/components/mainpage/floating/FloatingSection.tsx
  apps/web/src/components/mainpage/greeting/GreetingSection.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/src/components/mainpage/recruit/RecruitSection.tsx
Labels: size/L

#45 chore: product 디자인 QA 반영
  apps/web/src/components/mainpage/prouduct/Description.tsx
  apps/web/tailwind.config.js
Labels: size/XS

#46 feat: 플로팅 요소 인터랙션 반영
  apps/web/src/components/common/RecruitButton.tsx
  apps/web/src/components/mainpage/floating/FloatingSection.tsx
  apps/web/src/components/mainpage/floating/Footer.tsx
  apps/web/src/components/mainpage/floating/Header.tsx
  apps/web/src/components/mainpage/floating/handleScroll.ts
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/tailwind.config.js
Labels: size/L

#47 chore: 미완성 메뉴, 링크 주석처리
  apps/web/src/components/mainpage/floating/Header.tsx
  apps/web/src/components/mainpage/greeting/MakersIntodution.tsx
Labels: size/S

#48 feat: 메인 페이지 디테일 향상
  apps/web/src/app/(main)/page.tsx
  apps/web/src/components/mainpage/coreValue/CoreValueSection.tsx
  apps/web/src/components/mainpage/feedback/FeedbackCard.tsx
  apps/web/src/components/mainpage/feedback/FeedbackSection.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/src/components/mainpage/recruit/RecruitSection.tsx
Labels: size/M

#49 fix: 노션 블럭 에러 수정
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
Labels: size/XS

#50 feat: 노션 블럭 디자인 수정
  apps/web/src/app/recruit/[[...slug]]/layout.tsx
  apps/web/src/app/recruit/[[...slug]]/page.tsx
  apps/web/src/app/recruit/layout.tsx
  apps/web/src/components/notion/unofficial/TextRenderer.tsx
  apps/web/src/components/notion/unofficial/colors.ts
  apps/web/src/components/recruit/ToggleBlock.tsx
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
  apps/web/src/components/recruit/table/TableRowBlock.tsx
Labels: size/M

#51 fix: 스크롤 픽셀값, opacity 수정
  apps/web/src/components/mainpage/floating/FloatingSection.tsx
  apps/web/src/components/mainpage/floating/Header.tsx
Labels: size/S

#52 chore: 페이지 라우트 연결
  apps/web/src/components/common/RecruitButton.tsx
  apps/web/src/components/mainpage/floating/Footer.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
Labels: size/M

#53 feat: 디테일 수정
  apps/web/src/app/admin/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/components/mainpage/recruit/RecruitSection.tsx
  apps/web/src/components/recruit/customBlocks/EnterRecruitBlock.tsx
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
Labels: size/L

#54 feat: 활동 후기 추가
  apps/web/src/components/mainpage/feedback/FeedbackCard.tsx
  apps/web/src/components/mainpage/feedback/FeedbackSection.tsx
  apps/web/src/components/mainpage/feedback/data.ts
Labels: size/L

#55 fix: 외부 링크 연결 문제 해결
  apps/web/src/components/mainpage/feedback/FeedbackSection.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
Labels: size/S

#56 feat: URL 리다이렉트 추가
  apps/ssr-gateway/src/router/index.ts
  apps/ssr-gateway/src/router/redirect.ts
  apps/web/src/app/(redirect)/r/[key]/route.ts
Labels: size/S

#57 feat: 3D 로고 수정
  apps/web/src/components/common/MakersLogo3D/Light.tsx
  apps/web/src/components/common/MakersLogo3D/MakersLogoModel.tsx
  apps/web/src/components/common/MakersLogo3D/index.tsx
  apps/web/src/components/mainpage/greeting/GreetingSection.tsx
Labels: size/L

#58 feat: 3D 로고 색상 제거
  apps/web/src/components/common/MakersLogo3D/Light.tsx
  apps/web/src/components/common/MakersLogo3D/index.tsx
Labels: size/L

#59 feat: 깃허브 링크 추가
  apps/web/src/app/(main)/layout.tsx
  apps/web/src/app/recruit/[[...slug]]/layout.tsx
  apps/web/src/app/recruit/[[...slug]]/page.tsx
  apps/web/src/components/common/icons/GithubLogo.tsx
Labels: size/M

#60 refactor: Greeting 스크롤 영역 설정
  apps/web/src/components/mainpage/greeting/GreetingSection.tsx
Labels: size/XS

#61 feat: 리크루팅 페이지 제목 줄바꿈 문제 해결
  apps/web/src/components/recruit/recruitBlockUnofficial.tsx
Labels: size/XS

#62 chore: 문구 및 맞춤법, 문법 수정
  apps/web/src/components/mainpage/greeting/Intro.tsx
  apps/web/src/components/mainpage/greeting/MakersIntodution.tsx
  apps/web/src/components/mainpage/greeting/Missions.tsx
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
Labels: size/S

#63 feat: 리크루팅 페이지 로딩 성능 향상
  apps/ssr-gateway/src/cache/index.ts
  apps/ssr-gateway/src/router/recruit.ts
  apps/ssr-gateway/src/storage/kv.ts
Labels: size/L

#64 fix: 무한 로딩현상 수정
  apps/web/src/components/common/RenderingLoading.tsx
Labels: size/XS
