Repository sopt-makers/makers-page, pull requests merged in 2024-01, with the labels that each got.

#70 feat: 4기 모집 준비 반영
  apps/web/src/app/error.tsx
  apps/web/src/components/common/AboutRecruit/NoticeButton.tsx
  apps/web/src/components/common/AboutRecruit/RecruitButton.tsx
  apps/web/src/components/common/AboutRecruit/index.tsx
  apps/web/src/components/common/SimpleMenu.tsx
  apps/web/src/components/mainpage/floating/Footer.tsx
  apps/web/src/components/mainpage/greeting/Intro.tsx
  apps/web/src/components/mainpage/recruit/RecruitSection.tsx
Labels: size/L

#71 feat: 4기 지원 대응
  apps/web/src/components/common/AboutRecruit/RecruitButton.tsx
Labels: size/M

#72 chore : 플레이그라운드 이미지 변경
  apps/web/src/components/mainpage/prouduct/data.ts
Labels: size/XS

#73 chore : 앱팀 소개 이미지 변경
  apps/web/src/components/mainpage/prouduct/data.ts
Labels: size/XS

#74 feat: 플그 설명 수정
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
Labels: size/S

#75 feat : 앱팀 제품 설명 수정
  apps/web/src/components/mainpage/prouduct/ProductSection.tsx
  apps/web/src/components/mainpage/prouduct/data.ts
Labels: size/S

#76 fix: 노션 이미지 오류 수정
  apps/ssr-gateway/src/notion/api/client.ts
Labels: size/XS

#77 fix : INTRODUTION -> INTRODUCTION 으로 오타 수정
  apps/web/src/components/mainpage/floating/Header.tsx
Labels: size/XS

#78 refactor : RecruitButton 컴포넌트 스타일 및 남은 시간 표시 로직 변경
  apps/web/src/components/common/AboutRecruit/RecruitButton.tsx
Labels: size/M

#79 feat : 공홈 소개 이미지 변경
  apps/web/src/components/mainpage/prouduct/data.ts
Labels: size/XS

#80 chore : 메타데이터 title SOPT Makers -> SOPT makers 로 변경
  apps/web/src/app/layout.tsx
Labels: size/XS

#81 fix : 모집 마감기한 자정 -> 13시 로 변경
  apps/web/src/components/common/AboutRecruit/RecruitButton.tsx
Labels: size/XS

#82 fix : 모집 마감 날짜 토요일에서 수요일로 수정
  apps/web/src/components/common/AboutRecruit/RecruitButton.tsx
Labels: size/XS
